/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface Course {
  'id' : bigint,
  'categoryId' : bigint,
  'title' : string,
  'thumbnail' : string,
  'createdAt' : bigint,
  'description' : string,
  'instructorId' : Instructor,
}
export interface CreateCourseRequest {
  'categoryId' : bigint,
  'title' : string,
  'thumbnail' : string,
  'description' : string,
}
export interface CreateMaterialRequest {
  'url' : [] | [string],
  'title' : string,
  'blob' : [] | [ExternalBlob],
  'courseId' : bigint,
  'materialType' : string,
}
export type ExternalBlob = Uint8Array;
export type Instructor = Principal;
export interface Material {
  'id' : bigint,
  'url' : [] | [string],
  'title' : string,
  'blob' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'courseId' : bigint,
  'materialType' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMaterial' : ActorMethod<[CreateMaterialRequest], Material>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], Category>,
  'createCourse' : ActorMethod<[CreateCourseRequest], Course>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteMaterial' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoursesByCategory' : ActorMethod<[bigint], Array<Course>>,
  'getCoursesByInstructor' : ActorMethod<[Principal], Array<Course>>,
  'getMaterialsForCourse' : ActorMethod<[bigint], Array<Material>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCoursesByTitle' : ActorMethod<[string], Array<Course>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, string], undefined>,
  'updateCourse' : ActorMethod<[bigint, CreateCourseRequest], undefined>,
  'updateMaterial' : ActorMethod<[bigint, CreateMaterialRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];